language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
